### ISSUE TITLE
Error Cert/SSL

### ISSUE THREAD

**Issue by aspryne** [Nexinto/check_kubernetes#3]
When I run this :
sudo -u root /lib64/nagios/plugins/check_kubernetes -kubeconfig /etc/icingatest/config -type deployment -namespace itsma1 -name *

I got this error message do you know why ? i run it in root but crt is blocked

Cannot configure kubernetes client: invalid configuration: [unable to read client-cert /opt/kubernetes/ssl/server.crt for kubelet due to open /opt/kubernetes/ssl/server.crt:

**Comment by iljaweis** [comment]
I would guess it's because you did not embed the certs into your kubeconfig. Instead in your kubeconfig is a reference to where the cert would be in the filesystem.

**Comment by aspryne** [comment]
yes i understand but when i watch my kube/config i can see :
client-certificate: /opt/kubernetes/ssl/server.crt
client-key: /opt/kubernetes/ssl/server.key

The path is correct beacause its the same path on my master cluster. Maybe its a wrong certif ?

That was that, i changed the ca.cert and no more error thanks you
